[workspace]
members = [
    "ghostscope-compiler",
    "ghostscope-loader",
    "ghostscope-ui",
    "ghostscope-protocol",
    "ghostscope-platform",
    "ghostscope",
    "ghostscope-dwarf",
    "bins/dwarf-tool",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["swananan <jt26wzz@gmail.com>"]
license = "GPL"
keywords = ["ebpf", "gdb", "dwarf", "debugger"]

[workspace.dependencies]
log = "0.4.22"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
anyhow = "1.0.93"
tracing = "0.1.41"
tracing-log = "0.2.0"
thiserror = "2.0.12"
aya = "0.13.1"
aya-ebpf-bindings = "0.1.1"
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
futures = "0.3"
futures-util = "0.3"
crossterm = { version = "0.28", features = ["event-stream"] }
gimli = { path = "/mnt/500g/code/gimli" }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[patch.crates-io]
aya = { git = "https://github.com/aya-rs/aya", rev = "9261554e3c6ca37e401ec23a287a1ddf9cb1f26d" }
aya-ebpf-bindings = { git = "https://github.com/aya-rs/aya", rev = "9261554e3c6ca37e401ec23a287a1ddf9cb1f26d" }
