[package]
name = "ghostscope-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
chrono = "0.4"
aya-ebpf-bindings = { workspace = true }