[package]
name = "ghostscope-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
aya-ebpf-bindings = "0.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]