[package]
name = "ghostscope-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ghostscope-compiler = { path = "../ghostscope-compiler" }
aya = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true } 