[package]
name = "ghostscope-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ghostscope-compiler = { path = "../ghostscope-compiler" }
ghostscope-protocol = { path = "../ghostscope-protocol" }
aya = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
tokio = { workspace = true, features = ["io-util", "mio"] } 